"""company fix

Revision ID: 98964c2c4498
Revises: 2dbf8d904028
Create Date: 2025-05-15 11:47:46.133718

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "98964c2c4498"
down_revision = "2dbf8d904028"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("companies", sa.Column("name", sa.String(), nullable=False))
    op.drop_column("companies", "company")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "companies",
        sa.Column("company", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("companies", "name")
    # ### end Alembic commands ###
